-- Users Table
CREATE TABLE users {
    user_id INT(11) NOT NULL AUTO_INCREMENT,
    userName VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL,
    pwd VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIME,
    PRIMARY KEY (user_id)
}